"use client";

import { ArrowRight, CheckCircle2, Eye, EyeOff, LogIn, LogOut, RefreshCw, ShieldCheck, Ticket, UserPlus, WalletCards } from "lucide-react";
import Image from "next/image";
import { useEffect, useState, type FormEvent } from "react";

type AppUser = { id:number; name:string; email:string|null; phone:string|null; role:string; source:"visitor"|"staff"; verified:boolean };
type AppTicket = { id:number; ticket_name:string; event_name:string; state:string; short_code?:string; qr_url:string };
type AppWallet = { id:string; name:string; balance_cents:number; status:string };
type MeResponse = { ok:boolean; user:AppUser; tickets:AppTicket[]; wallets:AppWallet[]; linkage:string };
type AuthView = "welcome"|"login"|"register"|"verify";

const roleNames:Record<string,string>={admin:"Administrateur",committee:"Komiteelid",manager:"Bestuurder",pos:"Verkooppunt",scan:"Hekpersoneel",staff:"Personeel",visitor:"Besoeker"};

async function api(path:string,init?:RequestInit){
  const response=await fetch(path,{...init,credentials:"same-origin",headers:{"content-type":"application/json",...(init?.headers||{})}});
  const data=await response.json().catch(()=>({ok:false,error:"Die bediener het nie korrek geantwoord nie"}));
  if(!response.ok)throw new Error(data.error||"Iets het verkeerd geloop");
  return data;
}

function Splash(){return <main className="app-auth splash-screen"><div className="splash-glow"/><Image unoptimized src="/skou-crest.png" width={150} height={150} priority alt="Villiersdorp Landbou Skou"/><p>Villiersdorp Landbou Skou</p><h1>Welkom by die Skou-app</h1><span>Alles wat jy vir die skou nodig het, in jou hand.</span></main>}

export default function HomePage(){
  const [booting,setBooting]=useState(true),[view,setView]=useState<AuthView>("welcome"),[busy,setBusy]=useState(false);
  const [message,setMessage]=useState(""),[error,setError]=useState(""),[showPassword,setShowPassword]=useState(false);
  const [me,setMe]=useState<MeResponse|null>(null);

  const loadMe=async()=>{try{const data=await api("/api/app/me");setMe(data);setView(data.user.verified||data.user.source==="staff"?"welcome":"verify")}catch{setMe(null)}};
  useEffect(()=>{const timer=setTimeout(()=>setBooting(false),1250);const boot=queueMicrotask(()=>void loadMe());return()=>{clearTimeout(timer);void boot}},[]);

  const submitLogin=async(event:FormEvent<HTMLFormElement>)=>{event.preventDefault();setBusy(true);setError("");const form=new FormData(event.currentTarget);try{const result=await api("/api/app/login",{method:"POST",body:JSON.stringify({identifier:form.get("identifier"),password:form.get("password")})});await loadMe();if(result.requires_verification)setView("verify")}catch(err){setError(err instanceof Error?err.message:"Teken in het misluk")}finally{setBusy(false)}};
  const submitRegister=async(event:FormEvent<HTMLFormElement>)=>{event.preventDefault();setBusy(true);setError("");const form=new FormData(event.currentTarget);const password=String(form.get("password")||""),confirm=String(form.get("confirm")||"");if(password!==confirm){setError("Die twee wagwoorde stem nie ooreen nie");setBusy(false);return}try{const result=await api("/api/app/register",{method:"POST",body:JSON.stringify({name:form.get("name"),email:form.get("email"),phone:form.get("phone"),password})});setMessage(result.verification_sent?"Ons het 'n 6-syfer kode na jou e-pos gestuur.":"Jou rekening is geskep, maar die e-pos kon nie gestuur word nie. Probeer Stuur weer.");await loadMe();setView("verify")}catch(err){setError(err instanceof Error?err.message:"Registrasie het misluk")}finally{setBusy(false)}};
  const submitCode=async(event:FormEvent<HTMLFormElement>)=>{event.preventDefault();setBusy(true);setError("");const form=new FormData(event.currentTarget);try{await api("/api/app/verify-email",{method:"POST",body:JSON.stringify({code:form.get("code")})});setMessage("Dankie—jou rekening is bevestig en jou bestaande kaartjies en beursie is nagegaan.");await loadMe()}catch(err){setError(err instanceof Error?err.message:"Verifikasie het misluk")}finally{setBusy(false)}};
  const resend=async()=>{setBusy(true);setError("");try{await api("/api/app/resend-verification",{method:"POST",body:"{}"});setMessage("'n Nuwe kode is gestuur.")}catch(err){setError(err instanceof Error?err.message:"Ons kon nie die kode stuur nie")}finally{setBusy(false)}};
  const logout=async()=>{await api("/api/app/logout",{method:"POST",body:"{}"}).catch(()=>null);setMe(null);setMessage("");setError("");setView("welcome")};

  if(booting)return <Splash/>;
  if(me&&(me.user.verified||me.user.source==="staff"))return <Dashboard data={me} message={message} onLogout={logout}/>;

  return <main className="app-auth auth-screen"><section className="auth-brand"><Image unoptimized src="/skou-crest.png" width={64} height={64} priority alt="Villiersdorp Landbou Skou"/><div><p>Villiersdorp Landbou Skou</p><h1>{view==="welcome"?"Welkom":view==="login"?"Welkom terug":view==="register"?"Skep jou rekening":"Bevestig jou e-pos"}</h1></div></section>
    {view==="welcome"&&<section className="auth-card welcome-panel"><div className="welcome-art"><span>23–24 Oktober 2026</span><h2>Jou skou.<br/>Jou kaartjies.<br/>Jou app.</h2><p>Vind jou kaartjies, beursie en die jongste skou-inligting op een plek.</p></div><button className="app-primary" onClick={()=>{setView("register");setError("")}}><UserPlus/>Registreer</button><button className="app-secondary" onClick={()=>{setView("login");setError("")}}><LogIn/>Teken in</button></section>}
    {view==="login"&&<form className="auth-card auth-form" onSubmit={submitLogin}><p className="form-intro">Gebruik jou e-posadres, selfoonnommer of bestaande personeel-gebruikersnaam.</p><label>E-pos, selfoon of gebruikersnaam<input name="identifier" autoComplete="username" required placeholder="naam@voorbeeld.co.za"/></label><label>Wagwoord<span className="password-field"><input name="password" type={showPassword?"text":"password"} autoComplete="current-password" required/><button type="button" onClick={()=>setShowPassword(!showPassword)} aria-label="Wys of versteek wagwoord">{showPassword?<EyeOff/>:<Eye/>}</button></span></label>{error&&<p className="form-error">{error}</p>}<button className="app-primary" disabled={busy}>{busy?<RefreshCw className="spin"/>:<LogIn/>}{busy?"Besig…":"Teken in"}</button><button type="button" className="text-button" onClick={()=>setView("welcome")}>Terug</button></form>}
    {view==="register"&&<form className="auth-card auth-form" onSubmit={submitRegister}><p className="form-intro">Registreer as ’n gewone besoeker. Ons sal bestaande aankope veilig met jou rekening vergelyk.</p><label>Volle naam<input name="name" autoComplete="name" required/></label><label>E-posadres<input name="email" type="email" autoComplete="email" required/></label><label>Selfoonnommer<input name="phone" inputMode="tel" autoComplete="tel" placeholder="082 123 4567" required/></label><label>Wagwoord<input name="password" type="password" autoComplete="new-password" minLength={8} required/><small>Minstens 8 karakters.</small></label><label>Bevestig wagwoord<input name="confirm" type="password" autoComplete="new-password" minLength={8} required/></label>{error&&<p className="form-error">{error}</p>}<button className="app-primary" disabled={busy}>{busy?<RefreshCw className="spin"/>:<ArrowRight/>}{busy?"Skep rekening…":"Registreer"}</button><button type="button" className="text-button" onClick={()=>setView("welcome")}>Terug</button></form>}
    {view==="verify"&&<form className="auth-card auth-form verify-panel" onSubmit={submitCode}><ShieldCheck/><h2>Een laaste stap</h2><p>{message||"Tik die 6-syfer kode wat ons na jou e-pos gestuur het."}</p><input className="code-input" name="code" inputMode="numeric" autoComplete="one-time-code" pattern="[0-9]{6}" maxLength={6} placeholder="000000" required/>{error&&<p className="form-error">{error}</p>}<button className="app-primary" disabled={busy}><CheckCircle2/>Bevestig rekening</button><button type="button" className="app-secondary" disabled={busy} onClick={resend}>Stuur kode weer</button><button type="button" className="text-button" onClick={logout}>Teken uit</button></form>}
  </main>;
}

function Dashboard({data,message,onLogout}:{data:MeResponse;message:string;onLogout:()=>void}){
  const {user,tickets,wallets}=data;const walletTotal=wallets.reduce((sum,w)=>sum+w.balance_cents,0);
  return <main className="app-home"><header className="home-header"><Image unoptimized src="/skou-crest.png" width={52} height={52} priority alt="Villiersdorp Landbou Skou"/><div><small>Welkom terug</small><h1>{user.name}</h1></div><button onClick={onLogout} aria-label="Teken uit"><LogOut/></button></header>{message&&<p className="success-note"><CheckCircle2/>{message}</p>}<section className="access-banner"><div><small>JOU TOEGANG</small><strong>{roleNames[user.role]||user.role}</strong></div><ShieldCheck/></section><section className="summary-grid"><article><Ticket/><span><strong>{tickets.length}</strong><small>Kaartjies gevind</small></span></article><article><WalletCards/><span><strong>R {(walletTotal/100).toFixed(2)}</strong><small>Beursiebalans</small></span></article></section><section className="home-section"><div className="section-title"><div><small>MY KAARTJIES</small><h2>Gekoppelde kaartjies</h2></div><span>{tickets.length}</span></div>{tickets.length?<div className="ticket-list">{tickets.map(ticket=><a key={ticket.id} href={ticket.qr_url}><Ticket/><span><strong>{ticket.ticket_name}</strong><small>{ticket.event_name}{ticket.short_code?` · ${ticket.short_code}`:""}</small></span><b>{ticket.state==="unused"?"Gereed":ticket.state}</b></a>)}</div>:<EmptyState icon={<Ticket/>} title="Geen kaartjies gevind nie" text="Wanneer ’n aankoop se geverifieerde e-pos én selfoonnommer ooreenstem, verskyn dit outomaties hier."/>}</section><section className="home-section"><div className="section-title"><div><small>MY BEURSIE</small><h2>Skoubeursie</h2></div></div>{wallets.length?<div className="wallet-list">{wallets.map(wallet=><article key={wallet.id}><WalletCards/><div><small>{wallet.name}</small><strong>R {(wallet.balance_cents/100).toFixed(2)}</strong></div><span>Aktief</span></article>)}</div>:<EmptyState icon={<WalletCards/>} title="Geen beursie gekoppel nie" text="’n Bestaande beursie met dieselfde bevestigde kontakbesonderhede sal outomaties hier verskyn."/>}</section>{user.source==="staff"&&<a className="staff-link" href="https://www.villiersdorpskou.co.za/admin">Maak die bestaande bestuurstelsel oop <ArrowRight/></a>}<p className="privacy-line"><ShieldCheck/>Ons wys slegs aankope wanneer die rekening se bevestigde e-pos en selfoonnommer saam ooreenstem.</p></main>
}

function EmptyState({icon,title,text}:{icon:React.ReactNode;title:string;text:string}){return <div className="empty-state"><span>{icon}</span><strong>{title}</strong><p>{text}</p></div>}
